CREATE TABLE USER_OSO(
	ID SERIAL PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	FIRST_SURNAME VARCHAR(100) NOT NULL,
	SECOND_SURNAME VARCHAR(100),
	EMAIL VARCHAR(120) NOT NULL,
	PHONE VARCHAR(20),
	COMPANY_ID VARCHAR(4),
	PASSWORD VARCHAR(50) NOT NULL,
	EMAIL_VALIDATED BOOLEAN,
	ACCOUNT_LOCKED BOOLEAN,
	PASSWORD_EXPIRED BOOLEAN,
	ORGANIZATIONS_URL VARCHAR
);

--CREATE EXTENSION pgcrypto;

INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Manuel', 'Juarez', 'Rosas', 'manuel_juro@gmail.com', '55123456', 'MJRU', crypt('password1', gen_salt('md5')), TRUE, FALSE, FALSE, 'https://www.google.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Nubia', 'Arand', 'Sanchez', 'nubia_arsa@yahoo.com', '55987654', 'NASD', crypt('password2', gen_salt('md5')), FALSE, TRUE, FALSE, 'https://yahoo.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Victor', 'Burgos', 'Alegria', 'victor_bual@hotmail.com', '55135791', 'VBAT', crypt('password3', gen_salt('md5')), FALSE, FALSE, TRUE, 'http://www.microsoft.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Edgar', 'Contreras', 'Maya', 'edgar_coma@gmail.com', '55246802', 'ECMC', crypt('password4', gen_salt('md5')), TRUE, TRUE, FALSE, 'https://www.google.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Andrea', 'Cabrera', 'Suarez', 'andrea_casu@facebook.com', '55555555', 'ACSC', crypt('password5', gen_salt('md5')), FALSE, TRUE, TRUE, 'https://yahoo.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Valentina', 'Valdes', 'Valdivia', 'valentina_vava@yahoo.com', '55648762', 'VVVS', crypt('password6', gen_salt('md5')), TRUE, FALSE, TRUE, 'https://www.facebook.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Danut', 'Istrate', 'Dur', 'danut_isdu@ibm.com', '55732684', 'DIDS', crypt('password7', gen_salt('md5')), TRUE, TRUE, TRUE, 'http://www.ibm.com/us/en');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Mara', 'Aguilar', 'Ruiz', 'mara_agru@facebook.com', '55092437', 'MARO', crypt('password8', gen_salt('md5')), FALSE, FALSE, TRUE, 'https://www.facebook.com');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Juan', 'Jemes', 'Hidalgo', 'juan_jehi@ibm.com', '55162804', 'MARN', crypt('password9', gen_salt('md5')), FALSE, TRUE, FALSE, 'http://www.ibm.com/us/en');
INSERT INTO USER_OSO (NAME, FIRST_SURNAME, SECOND_SURNAME, EMAIL, PHONE, COMPANY_ID, PASSWORD, EMAIL_VALIDATED, ACCOUNT_LOCKED, PASSWORD_EXPIRED, ORGANIZATIONS_URL) VALUES ('Jazmin', 'Gles', 'Morales', 'jazmin_glmo@hotmail.com', '55139734', 'JGMD', crypt('password10', gen_salt('md5')), TRUE, FALSE, FALSE, 'http://www.microsoft.com');

SELECT * FROM USER_OSO;

--TRUNCATE TABLE USER_OSO;

--DROP TABLE USER_OSO;